version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    environment:
      - PORT=${BACKEND_PORT:-4000}
    env_file: .env
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:4000}
    depends_on:
      - backend
    env_file: .env
