version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - backend
