name: Explorer CI

on:
  push:
    paths:
      - 'trident-network-explorer/**'
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd trident-network-explorer/backend
          npm install

      - name: Run backend tests
        run: |
          cd trident-network-explorer/backend
          npm test || echo "No tests"

      - name: Install frontend dependencies
        run: |
          cd trident-network-explorer/frontend
          npm install

      - name: Build frontend
        run: |
          cd trident-network-explorer/frontend
          npm run build

      - name: Build backend Docker image
        run: |
          docker build -t explorer-backend:latest trident-network-explorer/backend

      - name: Build frontend Docker image
        run: |
          docker build -t explorer-frontend:latest trident-network-explorer/frontend

      - name: Docker Login
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag explorer-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/trident-explorer-backend:$TAG
          docker tag explorer-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/trident-explorer-frontend:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trident-explorer-backend:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trident-explorer-frontend:$TAG
