apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-config
  labels:
    app: trident
data:
  CHAIN_MODE: "rpc"
  TRIDENT_NODE_RPC_URL: "https://testnet.rpc.trident.network"
  REACT_APP_BACKEND_URL: "https://testnet-explorer-api.trident.network"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-node
  labels:
    app: trident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trident
  template:
    metadata:
      labels:
        app: trident
    spec:
      containers:
      - name: trident-node
        image: trident-network:latest
        envFrom:
        - configMapRef:
            name: trident-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8090
          name: http
        - containerPort: 50051
          name: grpc
        volumeMounts:
        - name: genesis
          mountPath: /app/genesis.json
          subPath: genesis.json
      volumes:
      - name: genesis
        configMap:
          name: trident-genesis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-genesis
  labels:
    app: trident
data:
  genesis.json: |
    {
      "config": {
        "chainId": "0x76a81b116bfaa26e",
        "blockTime": 2
      },
      "totalSupply": "1000000000",
      "validators": [
        {"address": "TVAL1PLACEHOLDER000000000000000000000", "stakingBalance": "50000000"},
        {"address": "TVAL2PLACEHOLDER000000000000000000000", "stakingBalance": "50000000"},
        {"address": "TVAL3PLACEHOLDER000000000000000000000", "stakingBalance": "50000000"}
      ],
      "accounts": [
        {"address": "TACC1PLACEHOLDER000000000000000000000", "balance": "10000"},
        {"address": "TACC2PLACEHOLDER000000000000000000000", "balance": "10000"},
        {"address": "TACC3PLACEHOLDER000000000000000000000", "balance": "10000"},
        {"address": "TACC4PLACEHOLDER000000000000000000000", "balance": "10000"},
      {"address": "TACC5PLACEHOLDER000000000000000000000", "balance": "10000"}
      ]
    }

---
apiVersion: v1
kind: Service
metadata:
  name: trident-node
  labels:
    app: trident
spec:
  selector:
    app: trident
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 50051
    targetPort: grpc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trident-node
  labels:
    app: trident
spec:
  rules:
  - host: explorer.testnet.trident.network
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trident-node
            port:
              name: http
