name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: Run tests
        run: |
          cd backend
          npm test --if-present
      - name: Build
        run: |
          cd backend
          npm run build --if-present
      - name: Build Docker image
        run: docker build -t trident-backend:latest ./backend
      - name: Docker Login
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag trident-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/trident-backend:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trident-backend:$TAG
