name: Backend CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Validate env
        run: |
          required_vars=(PORT CHAIN_MODE TRIDENT_NODE_RPC_URL FRONTEND_URL)
          for v in "${required_vars[@]}"; do
            grep -q "^$v=" backend/.env || { echo "$v missing"; exit 1; }
          done
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: Run tests
        run: |
          cd backend
          npm test --if-present
      - name: Build
        run: |
          cd backend
          npm run build --if-present
      - name: Build Docker image
        run: docker build -t trident-backend:latest ./backend
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          TAG=${{ github.event.release.tag_name }}
          docker tag trident-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/trident-backend:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trident-backend:$TAG
