name: CI

on:
  push:
    branches: ["main", "work"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - name: Lint frontend
      run: npm run lint
      working-directory: frontend
    - name: Test frontend
      run: npm test --silent
      working-directory: frontend
    - name: Build frontend
      run: npm run build
      working-directory: frontend
    - name: Install backend deps
      run: npm ci
      working-directory: backend
    - name: Lint backend
      run: npm run lint
      working-directory: backend
    - name: Test backend
      run: npm test --silent
      working-directory: backend
    - name: Build backend
      run: npm run build --if-present
      working-directory: backend
