name: Build

on:
  push:
    branches: ["main", "work"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build
      run: echo "Building Trident Network"
    - name: Test
      run: echo "Running tests" && true
    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t trident-network:latest .
    - name: Upload Docker image
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: trident-docker-image
        path: "**/Dockerfile"
