name: Frontend CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Validate env
        run: |
          required_vars=(PORT REACT_APP_BACKEND_URL REACT_APP_APP_TITLE REACT_APP_THEME_COLOR)
          for v in "${required_vars[@]}"; do
            grep -q "^$v=" frontend/.env.example || { echo "$v missing"; exit 1; }
          done
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Run tests
        run: |
          cd frontend
          npm test --if-present
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Build Docker image
        run: docker build -t trident-frontend:latest ./frontend
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          TAG=${{ github.event.release.tag_name }}
          docker tag trident-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/trident-frontend:$TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/trident-frontend:$TAG
